// Hints system for the impostor to understand the secret word
export const HINTS: { [key: string]: string } = {
  // Animais
  'Gato': 'Animal doméstico que mia',
  'Cachorro': 'Melhor amigo do homem',
  'Leão': 'Rei da selva',
  'Tigre': 'Animal listrado',
  'Elefante': 'Animal com tromba',
  'Girafa': 'Animal com pescoço comprido',
  'Zebra': 'Animal com listras',
  'Macaco': 'Primata inteligente',
  'Pinguim': 'Ave que não voa',
  'Pássaro': 'Animal que voa',
  'Peixe': 'Animal aquático',
  'Tubarão': 'Peixe predador',
  'Golfinho': 'Mamífero marinho inteligente',
  'Baleia': 'Maior animal do mundo',
  'Urso': 'Animal grande e forte',
  'Lobo': 'Canino selvagem',
  'Raposa': 'Animal astuto',
  'Coelho': 'Animal com orelhas compridas',
  'Veado': 'Animal com chifres',
  'Cobra': 'Réptil sem pernas',
  'Aranha': 'Aracnídeo que tece teias',
  'Borboleta': 'Inseto colorido',
  'Abelha': 'Inseto que produz mel',
  'Formiga': 'Inseto pequeno e trabalhador',
  'Coruja': 'Ave noturna',
  'Gavião': 'Ave de rapina',
  'Flamingo': 'Ave rosa',
  'Papagaio': 'Ave que fala',
  'Crocodilo': 'Réptil aquático',
  'Hipopótamo': 'Animal grande aquático',

  // Comida e Bebida
  'Pizza': 'Comida italiana com queijo',
  'Hambúrguer': 'Pão com carne',
  'Sorvete': 'Sobremesa gelada',
  'Chocolate': 'Doce marrom',
  'Café': 'Bebida escura quente',
  'Suco': 'Bebida de fruta',
  'Refrigerante': 'Bebida gaseificada',
  'Cerveja': 'Bebida alcoólica',
  'Vinho': 'Bebida de uva fermentada',
  'Champagne': 'Bebida de celebração',
  'Pão': 'Alimento básico',
  'Bolo': 'Doce de festa',
  'Biscoito': 'Alimento seco e crocante',
  'Doce': 'Alimento açucarado',
  'Caramelo': 'Doce pegajoso',
  'Brigadeiro': 'Doce brasileiro',
  'Beijinho': 'Doce de coco',
  'Pão de Queijo': 'Pão salgado brasileiro',
  'Feijoada': 'Prato brasileiro com feijão',
  'Churrasco': 'Carne grelhada',
  'Moqueca': 'Prato de peixe',
  'Acarajé': 'Salgado baiano',
  'Pastel': 'Salgado frito',
  'Coxinha': 'Salgado de forma cônica',
  'Empada': 'Salgado pequeno',
  'Lasanha': 'Massa em camadas',
  'Macarrão': 'Massa italiana',
  'Arroz': 'Grão branco',
  'Feijão': 'Legume escuro',
  'Salada': 'Alimento fresco',
  'Sopa': 'Alimento quente líquido',
  'Caldo': 'Líquido de cozimento',
  'Fruta': 'Alimento doce natural',
  'Maçã': 'Fruta vermelha',
  'Banana': 'Fruta amarela',
  'Laranja': 'Fruta cítrica',
  'Morango': 'Fruta vermelha pequena',
  'Melancia': 'Fruta grande vermelha',
  'Abacaxi': 'Fruta tropical',
  'Melão': 'Fruta doce',
  'Uva': 'Fruta pequena em cacho',
  'Pêra': 'Fruta verde',
  'Limão': 'Fruta ácida',
  'Coco': 'Fruta tropical branca',
  'Goiaba': 'Fruta tropical vermelha',
  'Manga': 'Fruta tropical doce',
  'Mamão': 'Fruta tropical laranja',
  'Cereja': 'Fruta vermelha pequena',
  'Amora': 'Fruta roxa',

  // Tecnologia
  'Computador': 'Máquina para trabalhar',
  'Celular': 'Telefone portátil',
  'Tablet': 'Dispositivo entre celular e computador',
  'Notebook': 'Computador portátil',
  'Teclado': 'Periférico com letras',
  'Mouse': 'Periférico para clicar',
  'Monitor': 'Tela de visualização',
  'Impressora': 'Máquina que imprime',
  'Scanner': 'Máquina que digitaliza',
  'Câmera': 'Dispositivo que fotografa',
  'Telefone': 'Aparelho de comunicação',
  'Fone': 'Acessório para ouvir',
  'Microfone': 'Dispositivo para capturar som',
  'Webcam': 'Câmera para vídeo',
  'Drone': 'Máquina voadora',
  'Smartwatch': 'Relógio inteligente',
  'Videogame': 'Console de jogos',
  'Controle': 'Periférico de jogo',
  'Joystick': 'Controle de jogo',
  'Carregador': 'Dispositivo para carregar bateria',
  'Internet': 'Rede global de computadores',
  'WiFi': 'Conexão sem fio',
  'Bluetooth': 'Tecnologia sem fio',
  'Aplicativo': 'Programa para celular',
  'Software': 'Programa de computador',
  'Programa': 'Conjunto de instruções',
  'Arquivo': 'Documento digital',
  'Pasta': 'Organizador de arquivos',
  'Desktop': 'Tela inicial',
  'Ícone': 'Símbolo visual',

  // Lugares e Pontos Turísticos Mundiais
  'Torre Eiffel': 'Monumento em Paris',
  'Big Ben': 'Relógio em Londres',
  'Estátua da Liberdade': 'Monumento em Nova York',
  'Cristo Redentor': 'Estátua no Rio de Janeiro',
  'Coliseu': 'Anfiteatro em Roma',
  'Pirâmides do Egito': 'Monumentos antigos',
  'Taj Mahal': 'Monumento na Índia',
  'Muro da China': 'Grande estrutura defensiva',
  'Stonehenge': 'Monumento pré-histórico',
  'Machu Picchu': 'Cidade inca no Peru',
  'Angkor Wat': 'Templo no Camboja',
  'Sagrada Família': 'Igreja em Barcelona',
  'Palácio de Versalhes': 'Palácio na França',
  'Kremlin': 'Fortaleza em Moscou',
  'Palácio de Buckingham': 'Residência real em Londres',
  'Basílica de São Pedro': 'Igreja no Vaticano',
  'Ópera de Sydney': 'Teatro na Austrália',
  'Ponte do Brooklyn': 'Ponte em Nova York',
  'Golden Gate': 'Ponte em São Francisco',
  'Ponte de Londres': 'Ponte histórica',

  // Cidades Mundiais
  'Paris': 'Cidade da luz',
  'Londres': 'Capital britânica',
  'Nova York': 'Cidade que nunca dorme',
  'Tóquio': 'Capital do Japão',
  'Berlim': 'Capital da Alemanha',
  'Roma': 'Cidade eterna',
  'Madri': 'Capital da Espanha',
  'Amsterdã': 'Cidade dos canais',
  'Barcelona': 'Cidade catalã',
  'Veneza': 'Cidade das águas',
  'Praga': 'Cidade das cem torres',
  'Viena': 'Capital da Áustria',
  'Moscou': 'Capital da Rússia',
  'Dubai': 'Cidade dos Emirados',
  'Singapura': 'Cidade-estado asiática',
  'Hong Kong': 'Metrópole asiática',
  'Bangkok': 'Capital da Tailândia',
  'Istambul': 'Cidade entre continentes',
  'Cairo': 'Capital do Egito',
  'Marrakech': 'Cidade marroquina',

  // Celebridades Brasileiras
  'Neymar': 'Jogador de futebol',
  'Pelé': 'Lenda do futebol',
  'Ronaldinho': 'Mágico do futebol',
  'Anitta': 'Cantora brasileira',
  'Ludmilla': 'Cantora de funk',
  'Pabllo Vittar': 'Cantora drag',
  'Gisele Bündchen': 'Modelo brasileira',
  'Bruna Marquezine': 'Atriz brasileira',
  'Camila Queiroz': 'Atriz brasileira',

  // São Paulo - Pontos Turísticos
  'Avenida Paulista': 'Avenida famosa de SP',
  'MASP': 'Museu de arte em SP',
  'Pinacoteca': 'Museu em SP',
  'Mercadão': 'Mercado tradicional de SP',
  'Rua 25 de Março': 'Rua comercial de SP',
  'Pátio do Colégio': 'Local histórico de SP',
  'Catedral da Sé': 'Igreja em SP',
  'Mosteiro de São Bento': 'Mosteiro em SP',
  'Parque do Ibirapuera': 'Parque em SP',
  'Museu do Ipiranga': 'Museu em SP',
  'Estádio do Morumbi': 'Estádio de futebol',
  'Estádio do Pacaembu': 'Estádio histórico',
  'Vila Madalena': 'Bairro artístico de SP',
  'Pinheiros': 'Bairro de SP',
  'Itaim Bibi': 'Bairro nobre de SP',
  'Sesc Pompéia': 'Centro cultural de SP',

  // Litoral
  'Guarujá': 'Praia perto de SP',
  'Ubatuba': 'Praia com cachoeiras',
  'Ilhabela': 'Ilha com praias',
  'Copacabana': 'Praia famosa do Rio',
  'Ipanema': 'Praia carioca',
  'Leblon': 'Praia do Rio',
  'Barra da Tijuca': 'Praia do Rio',
  'Búzios': 'Praia turística',
  'Cabo Frio': 'Praia com água fria',
  'Paraty': 'Cidade histórica litorânea',

  // Temas Brasileiros
  'Samba': 'Dança brasileira',
  'Carnaval': 'Festa brasileira',
  'Bossa Nova': 'Música brasileira',
  'Forró': 'Dança nordestina',
  'Capoeira': 'Arte marcial brasileira',
  'Futebol': 'Esporte nacional',
  'Açaí': 'Bebida e fruta roxa',
  'Guaraná': 'Bebida brasileira',
  'Cachaça': 'Bebida destilada',
  'Floresta Amazônica': 'Maior floresta do mundo',
  'Pantanal': 'Região de pântanos',
  'Cerrado': 'Bioma brasileiro',
  'Mata Atlântica': 'Floresta costeira',

  // Conceitos Abstratos
  'Tempo': 'Dimensão que passa',
  'Espaço': 'Dimensão que ocupa',
  'Verdade': 'Oposto da mentira',
  'Mentira': 'Informação falsa',
  'Paz': 'Ausência de conflito',
  'Guerra': 'Conflito armado',
  'Amor': 'Sentimento profundo',
  'Ódio': 'Sentimento negativo',
  'Alegria': 'Emoção positiva',
  'Tristeza': 'Emoção negativa',
  'Esperança': 'Sentimento otimista',
  'Desespero': 'Falta de esperança',
  'Liberdade': 'Ausência de restrição',
  'Prisão': 'Restrição de movimento',
  'Riqueza': 'Abundância de bens',
  'Pobreza': 'Falta de recursos',
  'Justiça': 'Equidade e imparcialidade',
  'Injustiça': 'Falta de equidade',
  'Bem': 'Ação positiva',
  'Mal': 'Ação negativa',
};

export function getHint(word: string): string {
  return HINTS[word] || 'Pense na categoria desta palavra';
}
